### ISSUE TITLE
constraint_residual array dimension problem

### ISSUE THREAD

**Issue by richie-live** [bhyang/diffusion-es#3]
https://github.com/bhyang/diffusion-es/blob/e4ad3995c5f50f1a437791e1dbc241ddf007be7e/nuplan-devkit/nuplan/planning/training/modeling/models/kinematic_diffusion_model.py#L239

Although this part does not seem to be used in the simulation, range(batch) obviously exceeds the first dimension of the array. How is this part of the code used?

**Comment by bhyang** [comment]
This is used for the reward-gradient guidance baseline (in those experiments batch_size is always 1), but we haven't gotten around to cleaning up that part of the code so now this does nothing. Should be safe to ignore it.
