### ISSUE TITLE
Question about the data part using in diffusion-es

### ISSUE THREAD

**Issue by Cocoon-Ray** [bhyang/diffusion-es#5]
Hi Thanks for your contributions, I'm a starter of the planning field. I was wondering whether the project use any sensor blob of nuPlan. That is to say, Whether should I download all the data (including map, logs, and sensor data).

**Comment by Cocoon-Ray** [comment]
It seems that nothing of the sensor_blob is needed.

**Comment by mrayur** [comment]
> sensor_blob

I met the same question as yours, could you tell me which part should be downloaded?
